name: Activity Logger

on:
  schedule:
    - cron: "0 */12 * * *" # اجرای خودکار هر ۱۲ ساعت
  workflow_dispatch: # قابلیت اجرای دستی از طریق GitHub Actions

jobs:
  log-activity:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Fetch user activity using GitHub API
      - name: Fetch user activity
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching user activity..." > activity_report.txt
          echo "--------------------------------" >> activity_report.txt

          # Fetch commits in the last 30 days
          COMMIT_COUNT=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/search/commits?q=author:${{ github.actor }}+committer-date:>$(date -d '30 days ago' +%Y-%m-%d)" \
            | jq '.total_count')
          echo "Commits in the last 30 days: $COMMIT_COUNT" >> activity_report.txt

          # Fetch pull requests created by the user
          PR_COUNT=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/search/issues?q=author:${{ github.actor }}+type:pr+created:>$(date -d '30 days ago' +%Y-%m-%d)" \
            | jq '.total_count')
          echo "Pull Requests created in the last 30 days: $PR_COUNT" >> activity_report.txt

          # Fetch issues opened by the user
          ISSUE_COUNT=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/search/issues?q=author:${{ github.actor }}+type:issue+created:>$(date -d '30 days ago' +%Y-%m-%d)" \
            | jq '.total_count')
          echo "Issues opened in the last 30 days: $ISSUE_COUNT" >> activity_report.txt

          echo "--------------------------------" >> activity_report.txt
          echo "Activity report collected successfully!"

      # Step 3: Update activity report in the repository
      - name: Update activity report
        run: |
          cp activity_report.txt activity_log.txt
          git add activity_log.txt
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Updated activity report"
          git pull --rebase origin main
          git push origin main
