name: Activity Logger

on:
  workflow_dispatch:

jobs:
  log-activity:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Fetch user activity using GitHub API
      - name: Fetch user activity
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching user activity..." > activity_report.txt
          echo "--------------------------------" >> activity_report.txt

          # Add timestamp to the log
          echo "Log generated at: $(date)" >> activity_report.txt
          echo "" >> activity_report.txt

          # Fetch commits in the last 30 days
          COMMIT_COUNT=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/search/commits?q=author:${{ github.actor }}+committer-date:>$(date -d '30 days ago' +%Y-%m-%d)" \
            | jq '.total_count')
          echo "Commits in the last 30 days: $COMMIT_COUNT" >> activity_report.txt

          # Fetch pull requests created by the user
          PR_COUNT=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/search/issues?q=author:${{ github.actor }}+type:pr+created:>$(date -d '30 days ago' +%Y-%m-%d)" \
            | jq '.total_count')
          echo "Pull Requests created in the last 30 days: $PR_COUNT" >> activity_report.txt

          # Fetch issues opened by the user
          ISSUE_COUNT=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/search/issues?q=author:${{ github.actor }}+type:issue+created:>$(date -d '30 days ago' +%Y-%m-%d)" \
            | jq '.total_count')
          echo "Issues opened in the last 30 days: $ISSUE_COUNT" >> activity_report.txt

          # Fetch repositories the user contributed to
          CONTRIBUTED_REPOS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/users/${{ github.actor }}/repos" \
            | jq '.[].full_name' | wc -l)
          echo "Repositories contributed to: $CONTRIBUTED_REPOS" >> activity_report.txt

          # Fetch stars gained by the user's repositories
          STAR_COUNT=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/users/${{ github.actor }}" \
            | jq '.public_repos')
          echo "Total stars across public repositories: $STAR_COUNT" >> activity_report.txt

          # Fetch review comments by the user
          REVIEW_COUNT=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/search/issues?q=type:pr+reviewed-by:${{ github.actor }}+updated:>$(date -d '30 days ago' +%Y-%m-%d)" \
            | jq '.total_count')
          echo "Pull Request Reviews in the last 30 days: $REVIEW_COUNT" >> activity_report.txt

          echo "--------------------------------" >> activity_report.txt
          echo "Activity report collected successfully!"

      # Step 3: Append activity report to the log file with timestamp
      - name: Append activity report to log
        run: |
          echo "" >> activity_log.txt
          echo "==========================================" >> activity_log.txt
          cat activity_report.txt >> activity_log.txt
          echo "==========================================" >> activity_log.txt

      # Step 4: Commit and push changes
      - name: Commit and push changes
        run: |
          git add activity_log.txt
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Updated activity log at $(date)"
          git pull --rebase origin main
          git push origin main
